### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by alecxe** [Gillespie59/eslint-plugin-angular#124]
Here the underlying js file where the error happens:

```javascript

/* eslint-disable camelcase */
"use strict";

xdescribe("t3Tags Directive", function () {
    var el, scope, controller, $httpBackend;

    beforeEach(module("ap"));

    beforeEach(inject(function ($compile, $rootScope, _$httpBackend_) {
        $httpBackend = _$httpBackend_;
        el = angular.element("<t3-tag></t3-tag>");
        $compile(el)($rootScope.$new());
        $rootScope.$digest();

        controller = el.controller();

        scope = el.isolateScope();// || el.scope();
    }));

    it("'getTagsArrayFromSearchTxt' function", function () {
        $httpBackend.expectGET("shared/tags/tag.html");
        expect(scope.getTagsArrayFromSearchTxt("co:E")).toEqual([]);
    });
});
```

`eslint` throws the error message on the following line:

```javascript

controller = el.controller();
```

Stacktrace:

```
$ node node_modules/eslint/bin/eslint.js src/shared/tags -c eslint.json

/Users/user/job/ap-ui-html/node_modules/eslint-plugin-angular/rules/ng_controller_name.js:22
                var name = node.arguments[0].value;
                                            ^
TypeError: Cannot read property 'value' of undefined
at EventEmitter.CallExpression (/Users/user/job/ap-ui-html/node_modules/eslint-plugin-angular/rules/ng_controller_name.js:22:45)
at EventEmitter.emit (events.js:117:20)
at Controller.controller.traverse.enter (/Users/user/job/ap-ui-html/node_modules/eslint/lib/eslint.js:725:25)
at Controller.__execute (/Users/user/job/ap-ui-html/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
at Controller.traverse (/Users/user/job/ap-ui-html/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
at EventEmitter.module.exports.api.verify (/Users/user/job/ap-ui-html/node_modules/eslint/lib/eslint.js:718:24)
at processFile (/Users/user/job/ap-ui-html/node_modules/eslint/lib/cli-engine.js:197:27)
at /Users/user/job/ap-ui-html/node_modules/eslint/lib/cli-engine.js:332:26
at /Users/user/job/ap-ui-html/node_modules/eslint/lib/util/traverse.js:61:17
at Array.forEach (native)
at traverse (/Users/user/job/ap-ui-html/node_modules/eslint/lib/util/traverse.js:41:54)
```

**Comment by alecxe** [comment]
This is because the `controller()` is called without arguments, `ng_controller_name` assumes there is at least one argument given - a controller name. I think we should not assume that and skip `controller()` calls without arguments.

**Comment by Gillespie59** [comment]
Problem solved. and 0.0.12 release pushed.
Thanks.

**Comment by alecxe** [comment]
Thank you for the quick fix!
