### ISSUE TITLE
node variable undefined causing gulp serve to exit

### ISSUE THREAD

**Issue by deepu105** [Gillespie59/eslint-plugin-angular#363]
There is an undefined handling error causing gulp serve to stop when there is a javascript error

Trace below. Im not very familiar with this plugin but a check for the node object would fix this but not sure if this is intended

we are using this in https://github.com/jhipster/generator-jhipster and this one is kind of a blocker for us

```

[BS] Reloading Browsers...
D:\Projects\test\testApp\node_modules\eslint-plugin-angular\rules\utils\angular-rule.js:199
        if (node.type === 'FunctionExpression' || node.type === 'FunctionDeclaration') {
                ^

TypeError: Cannot read property 'type' of undefined
    at findFunctionByNode (D:\Projects\test\testApp\node_modules\eslint-plugin-angular\rules\utils\angular-rule.js:199:17)
    at checkCallee (D:\Projects\test\testApp\node_modules\eslint-plugin-angular\rules\utils\angular-rule.js:147:25)
    at EventEmitter.callBoth (D:\Projects\test\testApp\node_modules\eslint-plugin-angular\rules\utils\angular-rule.js:85:13)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.leaveNode (D:\Projects\test\testApp\node_modules\eslint\lib\util\node-event-generator.js:51:22)
    at CodePathAnalyzer.leaveNode (D:\Projects\test\testApp\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:611:23)
    at CommentEventGenerator.leaveNode (D:\Projects\test\testApp\node_modules\eslint\lib\util\comment-event-generator.js:111:23)
    at Controller.controller.traverse.leave (D:\Projects\test\testApp\node_modules\eslint\lib\eslint.js:842:36)
    at Controller.__execute (D:\Projects\test\testApp\node_modules\eslint\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (D:\Projects\test\testApp\node_modules\eslint\node_modules\estraverse\estraverse.js:485:28)
    at EventEmitter.module.exports.api.verify (D:\Projects\test\testApp\node_modules\eslint\lib\eslint.js:836:24)
    at processText (D:\Projects\test\testApp\node_modules\eslint\lib\cli-engine.js:187:27)
    at CLIEngine.executeOnText (D:\Projects\test\testApp\node_modules\eslint\lib\cli-engine.js:671:26)
    at verify (D:\Projects\test\testApp\node_modules\gulp-eslint\index.js:20:23)
    at Transform._transform (D:\Projects\test\testApp\node_modules\gulp-eslint\index.js:68:18)
```

**Comment by deepu105** [comment]
@Gillespie59 any quick fix or workaround that we can do for this?

**Comment by deepu105** [comment]
If I change line 193 of `rules/utils/angular-rule.js` to below its working, if you think this the correct way to handle this I can do a PR
```
if (!node || (node.elements && node.elements.length === 0)) {
      return;
}
```

**Comment by remcohaszing** [comment]
I suppose it fails on invalid AngularJS code similar to:

```js
.factory('foo', []);
```

This doesn't mean it should crash the ESLint of course.

I see why your solution that would fix it. However, a better fix would be to add this check on line 196:

```js
if (node.type === 'ArrayExpression') {
    if (!node.elements.length) {
          return;
    }
    node = node.elements[node.elements.length - 1];
}
```

I'll fix this today, unless you want to make a PR. It requires some tests of course. ;)

**Comment by deepu105** [comment]
If you can fix please do so as Im very unfamilar with the plugin code and
your fix would be faster

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
actually it fails on things like this as well. But on any failure its shouldnt crash Eslint or gulp
```
(function() {
    'use strict';
    someVar
    angular
        .module('testapp')
        .controller('AuditsController', AuditsController);

```

**Comment by remcohaszing** [comment]
Sorry, can't do it right now.

If you need it that badly, just fork it, apply your solution to your fork and depend on you fork in the mean time.

**Comment by deepu105** [comment]
if you can do a release within few days that should be fine. Else we could just drop the plugin for now and add it back when there is a new version as I dont want to maintain a fork at this time. My hands are already pretty full

**Comment by deepu105** [comment]
we have a major release coming soon so we still have some more days

**Comment by deepu105** [comment]
@remcohaszing let us know when there is a new version and we will upgrade

**Comment by remcohaszing** [comment]
Sorry, I didn't get to it. Also I won't have time at least until after this weekend.

If I'm correct you should be able to depend on this branch as a temporary workaround: https://github.com/remcohaszing/eslint-plugin-angular/tree/fix-angular-rule

If it doesn't work, I'll take a look as soon as I have time, which will be somewhere next week. I will need an example how to trigger the error then though.

**Comment by deepu105** [comment]
for example you can use any js file with a random stray string some where
in it. If you cant reproduce let me know ill give you what fails for me

Thanks & Regards,
Deepu

**Comment by Gillespie59** [comment]
Can not reproduce this issue
