### ISSUE TITLE
function-type fails when empty array given as constant

### ISSUE THREAD

**Issue by jrencz** [Gillespie59/eslint-plugin-angular#376]
```js
(function () {
  'use strict';
  angular
    .module('foo', [])
    .constant('bar', []);
})();
```

```bash
~/.nvm/versions/node/v4.2.1/bin/node <hidden>/node_modules/eslint/bin/eslint.js --rulesdir= <hidden>/node_modules --format=checkstyle --stdin --stdin-filename file.js
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at findFunctionByNode ( <hidden>/node_modules/eslint-plugin-angular/rules/utils/angular-rule.js:199:17)
    at checkCallee ( <hidden>/node_modules/eslint-plugin-angular/rules/utils/angular-rule.js:147:25)
    at EventEmitter.callBoth ( <hidden>/node_modules/eslint-plugin-angular/rules/utils/angular-rule.js:85:13)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.leaveNode ( <hidden>/node_modules/eslint/lib/util/node-event-generator.js:51:22)
    at CodePathAnalyzer.leaveNode ( <hidden>/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:629:23)
    at CommentEventGenerator.leaveNode ( <hidden>/node_modules/eslint/lib/util/comment-event-generator.js:112:23)
    at Controller.traverser.traverse.leave ( <hidden>/node_modules/eslint/lib/eslint.js:890:36)
    at Controller.__execute ( <hidden>/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)

Process finished with exit code 1
```

By all means empty array is a valid constant.
Probably array is handled is a special way for annotated DI.

**Comment by Gillespie59** [comment]
This issue has been solved with this commit : https://github.com/Gillespie59/eslint-plugin-angular/commit/b918d022ce1e422a0e1f621dec8d006f7149ee96

**Comment by kayoub5** [comment]
@Gillespie59 this still fails using version `1.0.1`

**Comment by rarkins** [comment]
Should this be reopened?
