### ISSUE TITLE
How "angular/di": [2, "array, function, $inject"] will work?

### ISSUE THREAD

**Issue by elartix** [Gillespie59/eslint-plugin-angular#401]
Hi Team, 

I updated eslint plugin and received this issue. I have very large project with different  variants of dependencies injection. How I can resolve this?

`"eslint-plugin-angular": "~1.3.0",`
`"gulp-eslint": "~3.0.0",`

Exception:
```j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\config\config-validator.js:116
        throw new Error(message.join(""));
        ^

Error: j:\Projects\Elartix\{PROJECT}\.eslintrc:
	Configuration for rule "angular/di" is invalid:
	Value "array, function, $inject" must be an enum value.

    at validateRuleOptions (j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\config\config-validator.js:116:15)
    at j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\config\config-validator.js:163:13
    at Array.forEach (native)
    at Object.validate (j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\config\config-validator.js:162:35)
    at Object.load (j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\config\config-file.js:523:19)
    at loadConfig (j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\config.js:64:33)
    at getLocalConfig (j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\config.js:136:23)
    at Config.getConfig (j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\config.js:263:22)
    at processText (j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\cli-engine.js:223:27)
    at CLIEngine.executeOnText (j:\Projects\Elartix\{PROJECT}\node_modules\eslint\lib\cli-engine.js:749:26)
    at verify (j:\Projects\Elartix\{PROJECT}\node_modules\gulp-eslint\index.js:20:25)
    at Transform._transform (j:\Projects\Elartix\{PROJECT}\node_modules\gulp-eslint\index.js:70:17)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)

Process finished with exit code 1`

**Comment by Gillespie59** [comment]
can you share your .eslintrc file ? 
Thanks

**Comment by elartix** [comment]
Hi @Gillespie59 , Sure

```json
{
  "extends": "eslint:recommended",
  "plugins": ["angular"],
  "env": {
    "browser": true,
    "jasmine": true
  },
  "globals": {
    "angular": true,
    "module": true,
    "inject": true
  },
  "rules": {
    "quotes": [0, "single", "avoid-escape"],
    "eqeqeq": 0,
    "strict": 0,
    "no-console": 1,
    "no-cond-assign": 1,
    "no-empty": 1,
    "no-redeclare": 1,
    "no-unused-vars": 0,
    "no-undef": 0,
    "angular/angularelement": 0,
    "angular/di": [2, "array, function, $inject"],
    "angular/timeout-service": 0,
    "angular/controller-name": [2, "/[a-zA-Z]Controller$/"],
    "angular/controller-as": 0,
    "angular/controller-as-route": 0,
    "angular/controller-as-vm": 0,
    "angular/definedundefined": 1,
    "angular/document-service": 1,
    "angular/json-functions": 1,
    "angular/no-service-method": 0,
    "angular/on-watch": 0,
    "angular/typecheck-function": 1,
    "angular/typecheck-number": 1,
    "angular/typecheck-object": 1,
    "angular/typecheck-string": 1,
    "angular/window-service": 0,
    "angular/log": 1
  }
}
```

**Comment by Gillespie59** [comment]
I think you should use "angular/di": [2, "$inject"]", or "angular/di": [2, "function"]" or "angular/di": [2, "array]".

It depends of the syntax you prefer

**Comment by tilmanpotthof** [comment]
Just disable the rule, if you want to use all DI styles. Currently there is no way to specify more than one DI style, and I see no reason to extend the rule.

Does that answer your question?

**Comment by elartix** [comment]
Hi, 

Yes, I disabled this rule.

Thanx
