### ISSUE TITLE
Cannot read property 'name' of undefined when using avoid-scope-typos

### ISSUE THREAD

**Issue by davidmcclelland** [Gillespie59/eslint-plugin-angular#507]
Happy to provide any additional info I can to help reproduce, just let me know what you need.

eslint version@4.5.0
eslint-plugin-angular@3.1.0

Stacktrace:
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at check ([snip]\node_modules\eslint-plugin-angular\rules\avoid-scope-typos.js:24:75)
    at Linter.Identifier ([snip]\node_modules\eslint-plugin-angular\rules\avoid-scope-typos.js:31:17)
    at emitOne (events.js:101:20)
    at Linter.emit (events.js:188:7)
    at NodeEventGenerator.applySelector ([snip]\node_modules\eslint\lib\util\node-event-generator.js:265:26)
    at NodeEventGenerator.applySelectors ([snip]\node_modules\eslint\lib\util\node-event-generator.js:294:22)
    at NodeEventGenerator.enterNode ([snip]\node_modules\eslint\lib\util\node-event-generator.js:308:14)
    at CodePathAnalyzer.enterNode ([snip]\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:602:23)
    at Traverser.enter ([snip]\node_modules\eslint\lib\linter.js:926:36)
    at Traverser.__execute ([snip]\node_modules\estraverse\estraverse.js:397:31)
    at Traverser.traverse ([snip]\node_modules\estraverse\estraverse.js:501:28)

**Comment by Gillespie59** [comment]
Thanks for the issue. Can you also share the code causing this error ? I will add it to our unit tests.

**Comment by davidmcclelland** [comment]
I tried to log the node being entered in linter.js's traverser.traverse, but the output was rather verbose. I can't even figure out which file of mine is causing the exception. According to #508 it happens with the source for jquery 3.1.1 with attachments for it. You may be better off using that to test.

**Comment by yellowiscool** [comment]
Got the error with a `function broadcast() {}` in a factory. Renaming it to `broadcast2` or something else fixed the error.
