### ISSUE TITLE
Not found rule ng_no_ng_no_digest

### ISSUE THREAD

**Issue by albertosantini** [Gillespie59/eslint-plugin-angular#57]
It seems with version 0.0.4 (0.0.5 is not published) I get:

    Warning: Cannot find module './rules/ng_no_ng_no_digest'

**Comment by johnpapa** [comment]
Yes. this line needs to be fixed:
```
			'ng_no_digest': require('./rules/ng_no_ng_no_digest'),
```

**Comment by johnpapa** [comment]
and this one too:

```
			'ng_no_services': require('./rules/ng_no-service-ctrl'),
```

to 

```
			'ng_no_services': require('./rules/ng_no_services'),
```

**Comment by johnpapa** [comment]
Even with these, i still get 

```
/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:613
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'ng_interval_service' was not found.
    at /Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:613:27
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:586:16)
    at verify (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/index.js:21:25)
    at DestroyableTransform._transform (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/index.js:44:18)
    at DestroyableTransform.Transform._read (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

**Comment by Gillespie59** [comment]
@albertosantini can you test with latest changes ? If it is OK, I will deploy a quick 0.0.5 release. 

About your last error, @johnpapa, I can not reproduce it :s. Maybe @albertosantini  ?

**Comment by albertosantini** [comment]
I tested the master branch and it is ok.

**Comment by Gillespie59** [comment]
You do not have the last error found by @johnpapa ?

**Comment by albertosantini** [comment]
No, it is ok.

I get lint errors as `You should use the function syntax for DI  angular/ng_di`, where the code should be ok, but finally I open another issue about it.

**Comment by johnpapa** [comment]
I'd like to show this at ngConf tomorrow ... could you provide the steps you follow to use this so I can double check what I have tried?

Also, you should add a demo to this repo that can simply be pulled npm install'd and run.

**Comment by albertosantini** [comment]
@johnpapa I followed the steps describes in `Usage` section of the `README` to install the plugin.

Then I customized the eslint configuration for my project as described in https://github.com/Gillespie59/eslint-plugin-angular/issues/30.

If you clone my repo [argo](https://github.com/albertosantini/argo), you may use it as demo repo.

```
$ git clone git@github.com:albertosantini/argo.git
$ cd argo
$ npm install
...

$ npm test
...
```

**Comment by johnpapa** [comment]
I'm still getting errors after following the setup. I additionally installed eslint and gulp-eslint

```
$ gulp e
[20:48:52] Using gulpfile ~/_git/gulp-patterns/gulpfile.js
[20:48:52] Starting 'e'...
[20:48:52] Finished 'e' after 152 ms
/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:613
                    throw new Error("Definition for rule '" + key + "' was not
                          ^
Error: Definition for rule 'ng_interval_service' was not found.
    at /Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:613:27
    at Array.forEach (native)
    at EventEmitter.module.exports.api.verify (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/eslint/lib/eslint.js:586:16)
    at verify (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/index.js:21:25)
    at DestroyableTransform._transform (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/index.js:44:18)
    at DestroyableTransform.Transform._read (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/john/_git/gulp-patterns/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

**Comment by johnpapa** [comment]
This error is because the rule is misspelled. 

I noticed github has 0.0.6 but npm only has 0.0.5.

**Comment by johnpapa** [comment]
I was able to disable 4 rules and got it to work. These 4 cause errors saying rule not found: 

- ng_interval_service
- ng_service_name
- ng_timeout_service
- ng_window_service

Also, once I ran it with the remaining rules I got the ng_di error for the code blow (in a controller). It doesn't like the code where "states" beginds.



```javascript
        function getNavRoutes() {

            vm.navRoutes = states
                .filter(x).sort(y);
            function x (r) {
                return r.settings && r.settings.nav;
            }
            function y (r1, r2) {
                return r1.settings.nav - r2.settings.nav;
            }
        }
```
